### PR TITLE
Hydra Scala version detection heuristic fallbacks to module SDK version. Fix #37

### LINKED ISSUE #37: Cannot download Hydra on sbt imported project with scalaHome set
Here is the build.sbt file to use to reproduce the issue:

```
name := "bug"

scalaVersion := "2.11.8"

scalaHome := Some(file("/opt/scala-2.11.8/")) // <-- modify this to point to your scala home
```

Import the project into idea using the sbt build. Then, enable Hydra on the project and hit the Download button to fetch the Hydra artifacts. The following error is prompted:

> Could not determine Scala version in this project

Checking the idea.log provide the trail to understand the issue:

```
2017-12-22 15:44:21,812 [4923936]   INFO - s.plugins.hydra.HydraVersions$ - Could not retrieve Scala version in module 'bug' with compiler classpath: List(/opt/scala-2.11.8/lib/jline-2.12.1.jar, /opt/scala-2.11.8/lib/scala-compiler.jar, /opt/scala-2.11.8/lib/scala-continuations-library_2.11-1.0.2.jar, /opt/scala-2.11.8/lib/scala-continuations-plugin_2.11.8-1.0.2.jar, /opt/scala-2.11.8/lib/scala-library.jar, /opt/scala-2.11.8/lib/scala-parser-combinators_2.11-1.0.4.jar, /opt/scala-2.11.8/lib/scala-reflect.jar, /opt/scala-2.11.8/lib/scala-swing_2.11-1.0.2.jar, /opt/scala-2.11.8/lib/scala-xml_2.11-1.0.4.jar, /opt/scala-2.11.8/lib/scalap-2.11.8.jar)
```

The issue is the regex we use to determine the scala version (see [HydraVersions](https://github.com/triplequote/intellij-scala/blob/hydra-integration/scala/scala-impl/src/org/jetbrains/plugins/hydra/HydraVersions.scala#L17)).

One possible fix is to look inside the `scala-compiler.jar` and read the version from the `compiler.properties` file if there is no version appended to the `scala-compiler` jar.

### PR DESCRIPTION
**Pull request by dotta**
Our heuristic for extracting the scala version from the scala-compiler jar name
may not work if the scala-compiler jar in the classpath has no version happended
(this for instance can happen when importing an sbt project with the `scalaHome`
setting set to point to a locally installed Scala distribution).

The implemented solution consists in falling back to the module SDK Scala
version if the version cannot be extracted from the scala-compiler jar name.

### CODE REVIEW

File: scala/scala-impl/src/org/jetbrains/plugins/hydra/HydraVersions.scala [hunk 1]
```diff
@@ -14,31 +12,50 @@ object HydraVersions {
...
+    // matches `SDK-2.12.3` or the like. For the Scala project this is simply called `starr`, so we
+    // need to look inside and retrieve the actual classpath entries
+    val maybeScalaVersion = for {
+      compiler <- sdk.compilerClasspath.find(_.getName.contains(CompilerJarName))
+      matchedJar <- CompilerVersionRegex.findFirstMatchIn(compiler.getName)
+      version <- Option(matchedJar.group(1))
+    } yield version
+
+    // However, if the user has set the scalaHome in his sbt build, then the scala-compiler jar in
+    // the compiler classpath will likely not have the version happended, and hence the above heuristic
```
Comment (dragos) [inline scala/scala-impl/src/org/jetbrains/plugins/hydra/HydraVersions.scala]: happended -> appended

**Review by dragos — APPROVED** [review]

File: scala/scala-impl/src/org/jetbrains/plugins/hydra/HydraVersions.scala (hunk 1 above)
Comment (dotta) [reply scala/scala-impl/src/org/jetbrains/plugins/hydra/HydraVersions.scala]: Good catch :)
